Repository IIC3745-Testing-Grupo3/IIC3745-Grupo3-ProyectoB, pull requests merged in 2021-11, with the labels that each got.

#16 Multiple Reservations
  app/controllers/api/bookings_controller.rb
  app/javascript/packs/components/bookings/create/NewBookingForm.jsx
  config/routes.rb
Labels: feature, improvement, backend

#19 Feat/list movies test
  Gemfile
  Gemfile.lock
  app/javascript/packs/components/layout/Navbar.jsx
  spec/factories/movies.rb
  spec/features/movies/list_movie_spec.rb
  spec/rails_helper.rb
  spec/support/factory_bot.rb
Labels: test, frontend

#20 Avoid showing past movies
  app/controllers/api/movies_controller.rb
  app/javascript/packs/components/layout/Navbar.jsx
Labels: improvement, backend

#21 feat(seeds): add initial development seeds
  db/seeds.rb
Labels: feature, backend

#23 Fix/create movies without screenings
  app/controllers/api/movies_controller.rb
  app/javascript/packs/components/movies/create/NewMovieScreenings.jsx
Labels: fix, frontend, backend

#17 Add booking confirmation
  app/javascript/packs/api/screeningsApi.js
  app/javascript/packs/components/bookings/create/NewBookingConfirmation.jsx
  app/javascript/packs/components/bookings/create/NewBookingForm.jsx
  app/javascript/packs/components/bookings/create/NewBookingSuccessDialog.jsx
  app/javascript/packs/pages/NewBookingPage.jsx
Labels: feature, frontend

#15 Reservation of a movie with start date in the past
  app/controllers/api/bookings_controller.rb
  app/javascript/packs/components/bookings/create/NewBookingForm.jsx
Labels: fix, frontend

#24 Add screening relation to factory bot and a test for that
  spec/factories/movies.rb
  spec/factories/screenings.rb
  spec/features/movies/list_movie_spec.rb
Labels: test, backend

#25 Create booking test
  app/javascript/packs/components/bookings/create/NewBookingForm.jsx
  app/javascript/packs/components/bookings/create/NewBookingRoom.jsx
  spec/features/bookings/create_booking_spec.rb
  spec/spec_helper.rb
  spec/support/bookings_helper.rb
Labels: feature, test

#26 Add booked seat test to capybara
  spec/factories/booking.rb
  spec/features/bookings/check_booked_seat.rb
  spec/features/bookings/create_booking_spec.rb
Labels: test, backend

#27 Add testing instructions
  README.md
Labels: documentation
